gantt
dateFormat  DD-MM-YYYY
title Planning Movie Score

section Jeremy
Cahier des charges        :done,    a1, 24-04-2020,24-04-2020
Crawling des données      :active,  a2, 24-04-2020, 1w
Étude DB Neo4j ou OrientDB :         a3, after a2, 1w

section Steven
Insertion des données dans une DB :         a4, after a3, 1w
Analyse/ essais divers algorithmes de graphes :         a5, after a4, 1w
Frontend de l'application :         a6, after a5, 1w
Rapport : a7, after a2, 4w