gantt
dateFormat  DD-MM-YYYY
title Planning Movie Score

section Steven
Cahier des charges          :done,    a1, 24-04-2020,29-04-2020
Crawling des données        :active,  a2, after a1, 10d

section Jeremy
Parsing + insertion dans DB :         a4, after a2, 10d
Frontend de l'application   :         a6, after a5, 10d

section Jeremy + Steven
Étude technos DB            :         a3, after a2, 5d
Analyse algos graphes       :         a5, after a4, 7d
Rapport                     :         a7, after a5, 2w